apiVersion: apps/v1
kind: Deployment
metadata:
  name: achievementdeployment
  labels:
    app: ketchapp
    service: achievement

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketchapp
      service: achievement

  template:
    metadata:
      labels:
        app: ketchapp
        service: achievement
    spec:
      containers:
        - image: ketchapp/achievementservice:latest
          name: achievementservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50009
          env:
            - name: "PORT"
              value: "50009"

---
apiVersion: v1
kind: Service
metadata:
  name: achievementservice
spec:
  type: ClusterIP
  selector:
    app: ketchapp
    service: achievement
  ports:
    - name: grpc
      port: 50009
      targetPort: 50009

---
# remove this after testing
apiVersion: v1
kind: Service
metadata:
  name: achievement-test-node-port
spec:
  type: NodePort
  selector:
    app: ketchapp
    service: achievement
  ports:
    - name: grpc
      port: 50009
      targetPort: 50009
      nodePort: 30009
