apiVersion: apps/v1
kind: Deployment
metadata:
  name: recorddeployment
  labels:
    app: ketchapp
    service: record

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketchapp
      service: record

  template:
    metadata:
      labels:
        app: ketchapp
        service: record
    spec:
      containers:
        - image: ketchapp/recordservice:latest
          name: recordservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50006
          env:
            - name: "PORT"
              value: "50006"

---
apiVersion: v1
kind: Service
metadata:
  name: recordservice
spec:
  type: ClusterIP
  selector:
    app: ketchapp
    service: record
  ports:
    - name: grpc
      port: 50006
      targetPort: 50006

---
# remove this after testing
apiVersion: v1
kind: Service
metadata:
  name: test-node-port
spec:
  type: NodePort
  selector:
    app: ketchapp
    service: record
  ports:
    - name: grpc
      port: 50006
      targetPort: 50006
      nodePort: 30006
