apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsdeployment
  labels:
    app: ketchapp
    service: stats

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketchapp
      service: stats

  template:
    metadata:
      labels:
        app: ketchapp
        service: stats
    spec:
      containers:
        - image: ketchapp/statsservice:latest
          name: statsservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50008
          env:
            - name: "PORT"
              value: "50008"

---
apiVersion: v1
kind: Service
metadata:
  name: statsservice
spec:
  type: ClusterIP
  selector:
    app: ketchapp
    service: stats
  ports:
    - name: grpc
      port: 50008
      targetPort: 50008

---
# remove this after testing
apiVersion: v1
kind: Service
metadata:
  name: stats-test-node-port
spec:
  type: NodePort
  selector:
    app: ketchapp
    service: stats
  ports:
    - name: grpc
      port: 50008
      targetPort: 50008
      nodePort: 30008
